export {default as StudentProfile} from "../assets/instructor/dashboard/profile.svg"
export {default as StudentBg} from "../assets/instructor/dashboard/bg.svg"
export {default as AttedenceBg } from "../assets/instructor/dashboard/attedence_bg.svg"
export {default as UpdateCardBg } from "../assets/instructor/dashboard/update_card_bg.svg"
export {default as ClassBg } from "../assets/instructor/class/main-bg.svg"
export {default as OfflineClassIcon } from "../assets/instructor/class/online-class.svg"
export {default as InstructorLoginBg } from "../assets/instructor/login/login-bg.svg"
export {default as InstructorLoginGroups } from "../assets/instructor/login/objects.svg"
export {default as PaymentBg} from "../assets/instructor/payment/bg.svg"
export {default as TicketBg } from "../assets/instructor/Ticket/bg.svg"
export {default as CreateTicketRightSideImage} from "../assets/instructor/Ticket/createTicketRImage.svg"
export {default as SqlCourseImage} from "../assets/instructor/community/sql.svg"
export {default as JavaCourseImage } from "../assets/instructor/community/java.svg"
export {default as CommunityUser1} from "../assets/instructor/community/user1.svg"
export {default as CommunityUser2} from "../assets/instructor/community/user2.svg"
export {default as CommunityUser3} from "../assets/instructor/community/user3.svg"