export {default as StudentProfile} from "../assets/instructor/dashboard/profile.svg"
export {default as StudentBg} from "../assets/instructor/dashboard/bg.svg"
export {default as AttedenceBg } from "../assets/instructor/dashboard/attedence_bg.svg"
export {default as UpdateCardBg } from "../assets/instructor/dashboard/update_card_bg.svg"
export {default as ClassBg } from "../assets/instructor/class/main-bg.svg"
export {default as OfflineClassIcon } from "../assets/instructor/class/online-class.svg"
export {default as InstructorLoginBg } from "../assets/instructor/login/login-bg.svg"
export {default as InstructorLoginGroups } from "../assets/instructor/login/objects.svg"
export {default as PaymentBg} from "../assets/instructor/payment/bg.svg"
export {default as TicketBg } from "../assets/instructor/Ticket/bg.svg"
export {default as CreateTicketRightSideImage} from "../assets/instructor/Ticket/createTicketRImage.svg"
export {default as SqlCourseImage} from "../assets/instructor/community/sql.svg"
export {default as JavaCourseImage } from "../assets/instructor/community/java.svg"
export {default as CommunityUser1} from "../assets/instructor/community/user1.svg"
export {default as CommunityUser2} from "../assets/instructor/community/user2.svg"
export {default as CommunityUser3} from "../assets/instructor/community/user3.svg"
export {default as AttedenceMainBg} from "../assets/instructor/attedence/attedence_bg.svg"
export {default as AttedenceHeaderImg } from "../assets/instructor/attedence/attedence_header.svg"
export {default as AttedenceHeader2Img} from "../assets/instructor/attedence/attedence_header_2.svg"
export {default as ClassStudentViewCard} from "../assets/instructor/class/class-view/student-card.svg"
export {default as ClassInstructorViewCard } from "../assets/instructor/class/class-view/instructor-card.svg"
export {default as ClassCoordinatorViewCard } from "../assets/instructor/class/class-view/cooridinator-card.svg"
export {default as CourseBg } from "../assets/instructor/course/course_bg.svg"
export {default as CourseCardBg } from "../assets/instructor/course/course-card.svg"